### ISSUE TITLE
出现如下问题： COPY failed: stat /var/lib/docker/tmp/docker-builder141677891/docker-mario: no such file or directory

### ISSUE THREAD

**Issue by zyxzyxzyx** [bingohuang/play-docker-images#2]
如题

**Comment by bingohuang** [comment]
请问是在做哪一步的时候报了该错误？并最好能提供你当前OS信息、docker版本等信息

**Comment by zyxzyxzyx** [comment]
（1）OS信息：Linux zyx 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
（2）docker版本：Docker version 18.09.0, build 4d60db4
（3）是在这一步产生了问题：
root@zyx:~/docker-mario# docker build -t hub.c.163.com/bingohuang/docker-mario:1.0 .
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM hub.c.163.com/bingohuang/debian:163
 ---> 84f4f34589e6
Step 2/6 : MAINTAINER bingohuang <me@bingohuang.com>
 ---> Using cache
 ---> f8b7f899037b
Step 3/6 : RUN apt-get update && apt-get install -y nginx
 ---> Using cache
 ---> 8c8a0ee72978
Step 4/6 : COPY docker-mario /usr/share/nginx/www
COPY failed: stat /var/lib/docker/tmp/docker-builder141677891/docker-mario: no such file or directory
希望您能指出解决方案，我将不胜感激！

**Comment by zyxzyxzyx** [comment]
我在github上查到：
“Check .dockerignore
You probably trying to copy files that are in .dockerignore.”
不知是否与.dockerignore文件有关呢？

**Comment by bingohuang** [comment]
> 我在github上查到：
> “Check .dockerignore
> You probably trying to copy files that are in .dockerignore.”
> 不知是否与.dockerignore文件有关呢？

我这个目录不包含.dockerignore文件，从输出返回看是说 docker-mario这个目录不存在。
你检查下，在你的Dockerfile所在目录下，是否包含 `docker-mario` 这个目录? 你是否是在我的目录下执行的docker build？

**Comment by zyxzyxzyx** [comment]
嗯嗯，我之前确实没有在Dockerfile所在目录下，包含 docker-mario 这个目录。现在镜像可以构建成功了，本地运行也没有问题，但打开http://127.0.0.1:1989/后，只显示“Welcome to nginx!”.并没有所在的mario游戏页面，请问，是我哪一步做错了吗？（PS：我只是在Dockerfile所在的目录下，创建了一个空的docker-mario目录）

**Comment by bingohuang** [comment]
你把我的源码clone下来，在stage-01中有 docker-mario目录，可以运行游戏

**Comment by zyxzyxzyx** [comment]
![image](https://user-images.githubusercontent.com/23098739/49926586-d55f4280-fef6-11e8-86d0-52658a892a79.png)
终于成功了，感谢您不厌其烦的指导，多谢多谢，希望以后还有机会和您交流。

**Comment by bingohuang** [comment]
> ![image](https://user-images.githubusercontent.com/23098739/49926586-d55f4280-fef6-11e8-86d0-52658a892a79.png)
> 终于成功了，感谢您不厌其烦的指导，多谢多谢，希望以后还有机会和您交流。

:) 成功就好啊，多多学习！
那帮我把这个issue关了吧~

**Comment by zyxzyxzyx** [comment]
嗯嗯，再次表示感谢
